### ISSUE TITLE
Possible time format compatibility issue with GPSlogger 83

### ISSUE THREAD

**Issue by tneu33** [mendhak/gpsvisualizer#10]
GPS Visualizer version 7 does not produce time-based charts from gpx files written by GPSLogger 83.
Charts with distance as x-axis are ok, but charts with time as x-axis are blank.
- Distance over time / Elevation over time / Speed over time do not work
- Elevation over distance / Speed over distance are OK

I believe this is due to millisecond-resolution timestamp format introduced in GPSLogger 83.

**Comment by mendhak** [comment]
Sorry about that, I've fixed and pushed to market.
